"""SyntheticTrainee — Phase-2 stochastic transition model (brief §7.3, §7.6 Q4).

Provides (state, action, prescribed_volume[, prescribed_muscles]) -> next_state.
The LSTM world model (Phase 3) is trained on rollouts generated by this object,
which is itself a "plausible plus noise" surrogate — real outcome data would
replace it in production. See brief §7.6 Q4 for the explicit caveat.

Rules (intentionally simple, all parameters local to this module):
- Training actions raise fatigue + soreness on the targeted muscle chains, with
  magnitude proportional to ``prescribed_volume`` (full-body spreads across
  push / pull / legs / core).
- Rest (action_id=0) decays fatigue and *all* soreness multiplicatively.
- ``readiness = clip(1 - fatigue - mean(soreness), 0, 1)``.
- ``rolling_7d_volume`` updates via 7-day EWMA-like decay + today's volume.
- ``streak_days_trained``: +1 on any training action; reset to 0 on Rest.
- Gaussian noise (sigma configurable, default 0.05) is added to fatigue + each
  soreness channel; sigma=0 makes transitions fully deterministic.
"""

from __future__ import annotations

import numpy as np

from src.env.state import State

# Per-action muscle chains targeted (soreness gain locations).
# Keys: 0 Rest, 1 Push, 2 Pull, 3 Legs, 4 FullBody, 5 Conditioning, 6 Mobility.
_ACTION_MUSCLES: dict[int, tuple[str, ...]] = {
    0: (),
    1: ("push",),
    2: ("pull",),
    3: ("legs",),
    4: ("push", "pull", "legs", "core"),
    5: ("legs", "core"),
    6: ("core",),
}

# Volume → fatigue / soreness scaling constants (local design knobs).
_VOLUME_TO_FATIGUE = 0.03  # 10 units of volume → ~0.30 fatigue gain
_VOLUME_TO_SORENESS = 0.04  # 10 units of volume → ~0.40 soreness gain per chain
_REST_FATIGUE_DECAY = 0.55
_REST_SORENESS_DECAY = 0.60
_TRAIN_FATIGUE_DECAY = 0.85  # natural recovery between sessions
_TRAIN_SORENESS_DECAY = 0.85
_ROLLING_VOLUME_DECAY = 6.0 / 7.0  # ~7-day EWMA window


class SyntheticTrainee:
    """Stochastic state-evolution rules driven by the prescribed daily plan."""

    def __init__(
        self,
        rng: np.random.Generator | None = None,
        noise_sigma: float = 0.05,
    ) -> None:
        self.rng = rng if rng is not None else np.random.default_rng()
        self.noise_sigma = float(noise_sigma)

    def next_state(
        self,
        state: State,
        action_id: int,
        prescribed_volume: float = 0.0,
        prescribed_muscles: dict[str, float] | None = None,
    ) -> State:
        """Stochastic state-evolution under prescribed daily plan. Phase-2 transition."""
        if action_id not in _ACTION_MUSCLES:
            raise ValueError(f"unknown action_id={action_id}")
        is_rest = action_id == 0

        # Fatigue.
        if is_rest:
            new_fatigue = state.fatigue * _REST_FATIGUE_DECAY
        else:
            new_fatigue = state.fatigue * _TRAIN_FATIGUE_DECAY + _VOLUME_TO_FATIGUE * prescribed_volume
        new_fatigue = self._add_noise(new_fatigue)

        # Soreness per chain.
        sores = {
            "push": state.soreness_push,
            "pull": state.soreness_pull,
            "legs": state.soreness_legs,
            "core": state.soreness_core,
        }
        decay = _REST_SORENESS_DECAY if is_rest else _TRAIN_SORENESS_DECAY
        sores = {chain: value * decay for chain, value in sores.items()}
        if not is_rest:
            targeted = _ACTION_MUSCLES[action_id]
            if targeted:
                gain_per = _VOLUME_TO_SORENESS * prescribed_volume / len(targeted)
                for chain in targeted:
                    weight = (prescribed_muscles or {}).get(chain, 1.0)
                    sores[chain] = sores[chain] + gain_per * weight
        sores = {chain: self._add_noise(value) for chain, value in sores.items()}

        mean_sore = sum(sores.values()) / 4.0
        readiness = float(np.clip(1.0 - new_fatigue - mean_sore, 0.0, 1.0))

        rolling_vol = state.rolling_7d_volume * _ROLLING_VOLUME_DECAY + float(prescribed_volume)
        streak = 0 if is_rest else state.streak_days_trained + 1
        days_since_rest = 0 if is_rest else state.days_since_last_rest + 1
        balance = float(np.clip(sores["push"] - sores["pull"], -1.0, 1.0))

        return State(
            fatigue=float(new_fatigue),
            soreness_push=float(sores["push"]),
            soreness_pull=float(sores["pull"]),
            soreness_legs=float(sores["legs"]),
            soreness_core=float(sores["core"]),
            readiness=readiness,
            rolling_7d_volume=float(max(0.0, rolling_vol)),
            streak_days_trained=int(streak),
            days_since_last_rest=int(days_since_rest),
            muscle_balance_push_vs_pull=balance,
            adherence_signal=state.adherence_signal,
            weekly_progress=state.weekly_progress,
        )

    def _add_noise(self, value: float) -> float:
        """Add zero-mean Gaussian noise then clip to [0, 1]."""
        if self.noise_sigma > 0.0:
            value = value + float(self.rng.normal(0.0, self.noise_sigma))
        return float(np.clip(value, 0.0, 1.0))
